server:
  port: 19001

spring:
  redis:
    host: 115.28.138.45
    password: redispassword
    port: 6379
    database: 0

    jedis:
      pool:
        max-active: 10
        max-wait: 6000ms
        max-idle: 8
        min-idle: 5

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://ling07.top:3306/test?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    password: lgr123456
    username: root

mybatis:
  mapper-locations: classpath:mybatis-mappers/*Dao.xml
  type-aliases-package: com.springboot_test.entity
logging:
  level:
    com.springboot_test.dao: debug