server:
  port: 19001

spring:
  redis:
    host: 115.28.138.45
    password: redispassword
    port: 6379
    database: 0

    jedis:
      pool:
        max-active: 10
        max-wait: 6000ms
        max-idle: 8
        min-idle: 5
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://ling07.top:3306/test?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    password: lgr123456
    username: root

mybatis:
  mapper-locations: classpath:mybatis-mappers/*Dao.xml
  type-aliases-package: com.springboot_test.entity
logging:
  level:
    com.springboot_test.dao: debug
oss:
  endpoint: oss-cn-beijing.aliyuncs.com
  accessKeyId: LTAIi4DV4Aso36u1
  accessKeySecret: JEdNVS4MnEi0ayllmnWxqP9Dw7tx7F
  bucketName: lingoss0730
  domain: https://sycexe-keda-test.oss-cn-shenzhen.aliyuncs.com
  callbackUrl: https://test.keda.sycexe.com/kedatest/api-file/files/callback